.TH mutagen-pony 1 "February 20th, 2006"
.SH NAME
mutagen-pony \- scan a collection of MP3 files
.SH SYNOPSIS
\fBmutagen-pony\fR \fIdirectory\fR ...
.SH DESCRIPTION
\fBmutagen-pony\fR scans any directories given and reports on the
kinds of tags in the MP3s it finds in them. Ride the pony.
.PP
It is primarily intended as a debugging tool for Mutagen.
.SH AUTHORS
Michael Urman and Joe Wreschnig
