.TH mutagen-inspect 1 "May 27th, 2006"
.SH NAME
mutagen-inspect \- view Mutagen-supported audio tags
.SH SYNOPSIS
\fBmutagen-inspect\fR \fIfilename\fR ...
.SH DESCRIPTION
\fBmutagen-inspect\fR loads and prints information about an audio file
and its tags.
.PP
It is primarily intended as a debugging tool for Mutagen, but can
be useful for extracting tags from the command line.
.SH AUTHOR
Joe Wreschnig
