#!/usr/bin/python

import os, sys
import mutagen.id3

def display(filename):
    print "Tags in %s:" % filename
    try: id3 = mutagen.id3.ID3(filename)
    except mutagen.id3.error, err:
        print "Error:", str(err)
    else:
        print "Version:", ".".join(map(str, id3.version))
        strings = []
        for frame in id3.values():
            kw = []
            for attr in frame._framespec:
                val = getattr(frame, attr.name)
                if attr.name == "data":
                    try: kw.append("%s=[%d bytes]" % ( attr.name, len(val)))
                    except TypeError: kw.append("%s=%r" % (attr.name, val))
                else:
                    kw.append('%s=%r' % (attr.name, val))
            strings.append('%s(%s)' % (type(frame).__name__, ', '.join(kw)))
        strings.sort()
        print "\n".join(strings)
    print

if __name__ == "__main__":
    if len(sys.argv) == 1:
        raise SystemExit("Usage: %s filename.mp3 ..." % sys.argv[0])
    else:
        for filename in sys.argv[1:]: display(filename)
